---
# tasks file for nodejs

- block:
    - name: add apt key for nodejs
      apt_key:
        url: "http://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present

    - name: add nodejs repository
      apt_repository:
        repo: "deb http://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"

    - name: install nodejs
      become: yes
      become_method: sudo
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
        cache_valid_time: "{{ apt_cache_valid_time|default(omit) }}"
        install_recommends: no
      with_items:
        - "{{ nodejs_packages }}"

  become: yes
  tags:
    - nodejs
